spring:
  mvc:
    async:
      request-timeout: -1

  autoconfigure:
    exclude: org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO_PROD}
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  data:
    redis:
      host: ${REDIS_HOST_PROD}
      port: ${REDIS_PORT_PROD}
      password: ${REDIS_PASSWORD_PROD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_PROD}

logging:
  level:
    root: info
    com:
      example:
        team3final: info

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS_PROD}

websocket:
  allowed-origins: ${CORS_ALLOWED_ORIGINS_PROD}

app:
  ai:
    rag-store:
      url: ${AI_RAG_POSTGRES_URL_PROD}
      post-table-name: ${AI_MATCHING_POST_VECTOR_TABLE}

    matching:
      rag:
        similarity-threshold: ${AI_MATCHING_RAG_SIMILARITY_THRESHOLD}
        menu-similarity-threshold: ${AI_MATCHING_RAG_MENU_SIMILARITY_THRESHOLD}
        atmosphere-similarity-threshold: ${AI_MATCHING_RAG_ATMOSPHERE_SIMILARITY_THRESHOLD}
